version: "3.8"

services:
    php-api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php-api
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        networks:
            - mysql-network
        depends_on:
            - mysql

    mysql:
        image: mysql:latest
        container_name: mysql-db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db_test
            MYSQL_USER: root # Optional: Define a user
            MYSQL_PASSWORD: my-secret-pw
        ports:
            - "3333:3306"
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - mysql-network

volumes:
    db-data:

networks:
    mysql-network:
